main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'), 
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('increment_stock/<int:product_id>/', increment_stock, name='increment_stock'),
    path('decrement_stock/<int:product_id>/', decrement_stock, name='decrement_stock'),
    path('get-product/', get_product_json, name='get_product_json'),
    path('create-product-ajax/', add_product_ajax, name='add_product_ajax'),
    path('edit-product/<int:id>', edit_product, name='edit_product'),
    path('delete-item-ajax/<int:id>', delete_item_ajax, name='delete_item_ajax'),
    path('create-flutter/', create_product_flutter, name='create_product_flutter'),
    path('get-user-products/', get_user_products, name='get_user_products'),
]

marcard/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    price = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Product

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description"]

main/views.py
import json
from django.shortcuts import render
from django.http import *
from main.forms import ProductForm
from django.urls import reverse
from main.models import Product
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.core.serializers import serialize



@login_required(login_url='/login')
def show_main(request):
    products = Product.objects.filter(user=request.user)
    counter = 0
    
    for product in products:
        counter += 1

    if 'last_login' in request.COOKIES:
        last_login = request.COOKIES['last_login']
    else:
        last_login = 'N/A'  # Set a default value or handle the case when the key doesn't exist

    context = {
        'name': request.user.username, 
        'class': 'PBP E', 
        'products': products,
        'items' : counter,
        'last_login': last_login,
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "create_product.html", context)

def increment_stock(request, product_id):
    product = Product.objects.get(pk=product_id)
    product.price += 1
    product.save()
    return redirect('main:show_main')

def decrement_stock(request, product_id):
    product = Product.objects.get(pk=product_id)
    if product.price > 0:
        product.price -= 1
        product.save()
    return redirect('main:show_main')

def show_xml(request):
    data = Product.objects.all()

def show_xml(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Product.objects.all()

def show_json(request):
    data = Product.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def edit_product(request, id):
    # Get product berdasarkan ID
    product = Product.objects.get(pk = id)

    # Set product sebagai instance dari form
    form = ProductForm(request.POST or None, instance=product)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))

    context = {'form': form}
    return render(request, "edit_product.html", context)

def delete_product(request, id):
    # Get data berdasarkan ID
    product = Product.objects.get(pk = id)
    # Hapus data
    product.delete()
    # Kembali ke halaman awal
    return redirect('main:show_main')

def get_product_json(request):
    product_item = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', product_item))

@csrf_exempt
def add_product_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        user = request.user

        new_product = Product(name=name, price=price, description=description, user=user)
        new_product.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()


@csrf_exempt
def delete_item_ajax(request, id):
    if request.method == 'DELETE':
        product = get_object_or_404(Product, pk=id)
        product.delete()
        return HttpResponse(b"DELETED", status=204)
    return HttpResponseNotFound()

@csrf_exempt
def create_product_flutter(request):
    if request.method == 'POST':
        data = json.loads(request.body)

        # Periksa apakah pengguna yang membuat permintaan sesuai dengan pemilik produk
        if request.user.is_authenticated and request.user == data.get("user"):
            new_product = Product.objects.create(
                user=request.user,
                name=data["name"],
                price=int(data["price"]),
                description=data["description"]
            )
            return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
@login_required
def get_user_products(request):
    if request.method == 'GET':
        user_products = Product.objects.filter(user=request.user)
        serialized_products = serialize('json', user_products)
        return JsonResponse({"data": serialized_products}, status=200, safe=False)
    else:
        return JsonResponse({"status": "error", "message": "Method not allowed"}, status=405)

main/templates/create_product.html
{% extends 'base.html' %} 

{% block content %}

<style>
    .equal-width-cols {
        width: 33.33%;
    }
    body {
        background-color: #16191c;
    }
</style>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h1 class="card-title">
                        Add New Card
                    </h1>
                    <form method="POST">
                        {% csrf_token %}
                        <table class="table">
                            <tr>
                                <td class="equal-width-cols">{{ form.name.label_tag }}</td>
                                <td class="equal-width-cols">{{ form.name }}</td>
                            </tr>
                            <tr>
                                <td class="equal-width-cols">{{ form.price.label_tag }}</td>
                                <td class="equal-width-cols">{{ form.price }}</td>
                            </tr>
                            <tr>
                                <td class="equal-width-cols">{{ form.description.label_tag }}</td>
                                <td class="equal-width-cols">{{ form.description }}</td>
                            </tr>
                        </table>
                        <div class="text-center">
                            <input type="submit" class="btn btn-primary" value="Add"/>
                        </div>
                    </form>

                    {% if messages %}
                    <ul class="list-group">
                        {% for message in messages %}
                        <li class="list-group-item">{{ message }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    <div class="text-center mt-3">
                        <button type="button" class="custom-btn5" onclick="history.back()">Kembali</button>
                        <style>
                            .custom-btn5 {
                                background-color: green;
                                color: white;
                                border: none;
                                border-radius: 5px;
                                padding: 7px 20px; 
                            }
                        </style>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock %}

main/templates/edit_product.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<style>
    body {
        background-color: #16191c;
    }
</style>

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h1 class="text-center">Edit Product</h1>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        <table class="table">
                            {{ form.as_table }}
                        </table>
                        <div class="text-center">
                            <button type="submit" class="btn btn-primary">Edit Product</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}
<style>
    body {
        background-color: #16191c;
    }
</style>


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card mt-5">
                <div class="card-header">
                    <h1 class="card-title">Login</h1>
                </div>
                <div class="card-body">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Username:</label>
                            <input type="text" name="username" id="username" placeholder="Username" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="password">Password:</label>
                            <input type="password" name="password" id="password" placeholder="Password" class="form-control">
                        </div>
                        <div class="form-group mt-2">
                            <input class="btn btn-primary" type="submit" value="Login">
                        </div>
                    </form>
                    {% if messages %}
                        <ul class="list-unstyled">
                            {% for message in messages %}
                                <li class="text-danger">{{ message }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <p>Don't have an account yet? <a href="{% url 'main:register' %}">Register Now</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block content %}
    <style>
        body {
            background-color: #16191c;
        }
    </style>
    <style>
        table.table thead tr td:first{
            background-color: rgb(202, 255, 136);
            color: black;
        }
    </style>
    
    <style>
        table.table tbody tr:last-child td{
            background-color: rgb(19, 7, 73);
            color: white;
        }
    </style>
    

    <nav class="navbar bg-body-tertiary">
        <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">Marcard</span>
        <div class="d-flex justify-content-end">
        <form>
        <a href="{% url 'main:logout' %}">
        <button class="btn btn-outline-success me-2" type="button">Logout</button>
        </a>
        </form>
    </div>
    </nav>

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card mx-auto mt-3">
                    <div class="card-body text-center">
                        <p class="card-text">Hello! Nice to see you {{ name }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <style>
        .custom-card {
            width: 90%;
            margin: 20px auto;
        }
    </style>
    
    <div class="card custom-card">
        <div class="card-body">
            <table id="product_table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th style="white-space: nowrap; background-color:lightblue">Name</th>
                        <th style="white-space: nowrap; background-color:lightblue">Price</th>
                        <th style="white-space: nowrap; background-color:lightblue">Description</th>
                        <th style="white-space: nowrap; background-color:lightblue">Date Added</th>
                        <th style="white-space: nowrap; background-color:lightblue">Actions</th>
                    </tr>
                </thead>
            </table>
            <div id="product_cards" class="card-container">
            </div>
            <p class="text-center">Kamu menyimpan <span id="item-count">{{items}}</span> item pada aplikasi ini<p>
            <div style="text-align: center;">
                <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Product by AJAX</button>
            </div>
        </div>
    </div>
    
    </div>

    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Product</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name" class="col-form-label">Name:</label>
                            <input type="text" class="form-control" id="name" name="name"></input>
                        </div>
                        <div class="mb-3">
                            <label for="price" class="col-form-label">Price:</label>
                            <input type="number" class="form-control" id="price" name="price"></input>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="col-form-label">Description:</label>
                            <textarea class="form-control" id="description" name="description"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Product</button>
                </div>
            </div>
        </div>
    </div>

    
    <div class="container text-center mt-3">
        <h5 style="color: white;">Sesi terakhir login: {{ last_login }}</h5>
    </div>

    

    <script>
        async function getProducts() {
        return fetch("{% url 'main:get_product_json' %}").then((res) => res.json())
        }

        async function refreshProducts() {
            const products = await getProducts();
            const itemCountElement = document.getElementById("item-count");

        itemCountElement.textContent = products.length;
            let htmlString = `<table id="product_table" class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Price</th>
                        <th>Description</th>
                        <th>Date Added</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>`;
                    
            
        products.forEach((item) => {
            htmlString += `
                <tr>
                    <td>${item.fields.name}</td>
                    <td>${item.fields.price}</td>
                    <td>${item.fields.description}</td>
                    <td>${item.fields.date_added}</td>
                    <td class="action-column">
                        <div class="btn-group" role="group">
                            <a href="increment_stock/${item.pk}/">
                                <button type="submit" class="btn custom-btn1">+</button>
                            </a>
                            <a href="decrement_stock/${item.pk}/">
                                <button type="submit" class="btn custom-btn2">-</button>
                            </a>
                            <a href="edit-product/${item.pk}">
                                <button type="submit" class="btn custom-btn3">Edit</button>
                            </a>
                            <button class="btn custom-btn4" data-url="{% url 'main:delete_item_ajax' 123 %}" onclick="deleteProduct(this, ${item.pk})">Delete</button>
                        </div>
                    </td>
                </tr>`;
        });

        htmlString += `</tbody></table>`;
        
        document.getElementById("product_table").innerHTML = htmlString;

        const cardContainer = document.getElementById("product_cards");

        cardContainer.innerHTML = "";

        products.forEach((item) => {
            // Create a card for each item
            const card = document.createElement("div");
            card.className = "product-card";

            card.innerHTML = `
            <h3>${item.fields.name}</h3>
            <p><strong>Price:</strong> $${item.fields.price}</p>
            <p><strong>Description:</strong> ${item.fields.description}</p>
            <p><strong>Date Added:</strong> ${item.fields.date_added}</p>
            <div class="action-buttons">
                <div class="price-buttons">
                    <a href="increment_stock/${item.pk}" class="btn custom-btn1">+</a>
                    <a href="decrement_stock/${item.pk}" class="btn custom-btn2">-</a>
                </div>
                <div class="edit-delete-buttons">
                    <a href="edit_product/${item.pk}" class="btn custom-btn3">-</a>
                    <button class="btn custom-btn4" data-url="{% url 'main:delete_item_ajax' 123 %}" onclick="deleteProduct(this, ${item.pk})">Delete</button>
                </div>
            </div>
            `;

            cardContainer.appendChild(card);
        });
    }

    function deleteProduct(button, id) {
        let url = button.getAttribute('data-url').replace('123', id);
        fetch(url, {
            method: "DELETE",
        }).then(refreshProducts)
    }


    refreshProducts();


    function addProduct() {
        fetch("{% url 'main:add_product_ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }

    document.getElementById("button_add").onclick = addProduct
    

    </script>

<style>
    .card-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-start;
    }

    .product-card {
    border: 1px solid #ccc;
    padding: 10px;
    margin: 10px;
    background-color: #fff;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    border-radius: 5px;
    width: calc(33.33% - 20px);
    box-sizing: border-box;
    text-align: center;
    }

    .product-card:hover {
        transform: scale(1.05);
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
    }

    .product-card h3 {
    font-size: 20px;
    }

    .product-card p {
    margin: 5px 0;
    }

    .action-buttons {
    margin-top: 10px;
    }

    .custom-btn1, .custom-btn2, .custom-btn3, .custom-btn4 {
        text-decoration: none;
        padding: 5px 15px;
        margin: 5px;
        border-radius: 5px;
        color: #fff;
        width: 150px;
    }
    

    .custom-btn1 {
    background-color: grey;
    }

    .custom-btn2 {
    background-color: grey;
    }

    .custom-btn3 {
    background-color: yellow;
    color: black;
    }

    .custom-btn4 {
    background-color: red;
    }

    @media screen and (max-width: 768px) {
    .product-card {
        width: calc(50% - 20px);
    }
    }

    @media screen and (max-width: 480px) {
    .product-card {
        width: 100%;
    }
    }


</style>

{% endblock content %}

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %} 

<style>
    body {
        background-color: #16191c; 
    }
</style>


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card mt-5">
                <div class="card-body">
                    <h1 class="card-title">Register</h1>

                    <form method="POST">
                        {% csrf_token %}
                        <table class="table">
                            {{ form.as_table }}
                        </table>
                        <div class="text-center">
                            <input type="submit" class="btn btn-primary" value="Register"/>
                        </div>
                    </form>
                    <div class="text-center mt-3">
                        <button type="button" class="custom-btn5" onclick="history.back()">Kembali</button>
                        <style>
                            .custom-btn5 {
                                background-color: green; 
                                color: white; 
                                border: none; 
                                border-radius: 5px;
                                padding: 7px 20px; 
                            }
                        </style>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock content %}